# Generated by Django 4.1.7 on 2023-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='Design_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
