# Generated by Django 4.1.7 on 2023-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0002_servicedb_design_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='designdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicedb',
            name='Design_Name',
        ),
    ]
