# Generated by Django 4.1.7 on 2023-08-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0003_designdb_remove_servicedb_design_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designdb',
            name='Design_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Dimage'),
        ),
    ]
