# Generated by Django 4.1.7 on 2023-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0004_designdb_description_designdb_design_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='pimage')),
            ],
        ),
    ]
