# Generated by Django 4.1.7 on 2023-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0005_projectdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
