# Generated by Django 4.1.7 on 2023-08-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadmin', '0006_jobad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobad',
            new_name='jobdb',
        ),
    ]
