# Generated by Django 4.1.7 on 2023-08-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicantdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Resume', models.FileField(upload_to='resumes')),
            ],
        ),
    ]
