# Generated by Django 4.1.7 on 2023-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhuser', '0002_applicantdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
